id: P42994958
initial_creation_type: input
source_metadata:
  title: Kadam Series
  language: bo
  description: Art
  volume:
    3753504eba7046cc8ad44c909120e55c:
      title: Description of a Kadam Thangka
      parent: Art
created_at: '2022-03-01T04:01:24.557402'
last_modified_at: '2022-03-01T04:01:24.557404'
